[package]
name = "bg-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
jj-lib.workspace = true
tokio.workspace = true
futures.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
bg-proto = { path = "../bg-proto" }

[dev-dependencies]
tempfile.workspace = true
