[package]
name = "bg-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "bg"
path = "src/main.rs"

[[bin]]
name = "bgd"
path = "src/bin/bgd.rs"

[dependencies]
clap.workspace = true
tokio.workspace = true
serde_json.workspace = true
anyhow.workspace = true
hyper.workspace = true
hyper-util.workspace = true
hyperlocal.workspace = true
http-body-util.workspace = true
tracing-subscriber.workspace = true
bg-proto = { path = "../bg-proto" }
bg-daemon = { path = "../bg-daemon" }
